### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by durraniu** [rogerlew/undaqTools#1]
Hi Roger,

Thank you for your awesome package. I am trying to read in a DAQ file since the automation updates to the simulator. But some, not all, files produce an error. I am not sure if it is because something is outdated in undaqTools. Could you please have a look? Thank you.

### DAQ file
I have 2 DAQ files that I am trying to read in. The `WithTraffic` file is successfully read in, but the `NoTraffic` file produces the error below. You can download both files [here](https://uwin365-my.sharepoint.com/:f:/g/personal/talukden_uwindsor_ca/Es2vBKhjJM9ChWTUsn9su7YBhp98fbVP-ZTdV9y6LBBKNg?e=6RH6U5)  

### Code and Error  

I have the following script that I run with `python 02_convert_daq_files_to_hdf5.py`. But it produces the error below.

```
# Changing directory to the folder where DAQ files reside ----------------------------
import os
os.chdir("C:\\Users\\HP\\Desktop\\driving_sim\\data\\daq")



# Getting the names of all DAQ files
import glob
ctnames = glob.glob('*.daq')
#print(ctnames)




# Importing and using undaq tools to convert all DAQ files to HDF5 format
# import sys

from undaqTools import Daq
for n in ctnames:
  daq = Daq()
  x = daq.read(n)
  daq.write_hd5(x)
  # print(type(x))


```
Traceback (most recent call last):
  File "02_convert_daq_files_to_hdf5.py", line 30, in <module>
    x = daq.read(n)
  File "C:\Python27\lib\site-packages\undaqTools\daq.py", line 295, in read_daq
    self._interpolate_missing_frames()
  File "C:\Python27\lib\site-packages\undaqTools\daq.py", line 559, in _interpolate_missing_frames
    for j in xrange(elem.numvalues)]
  File "C:\Python27\lib\site-packages\numpy\lib\function_base.py", line 1412, in interp
    return interp_func(x, xp, fp, left, right)
TypeError: Cannot cast array data from dtype('S1') to dtype('float64') according to the rule 'safe'
```


```

**Comment by rogerlew** [comment]
Hi Umair,

I'm not able to download the files. It is asking me to login with U of
Windsor Credentials.

Roger

**Comment by durraniu** [comment]
Thanks a lot for responding, Roger. I later found out that other files were successfully saved as hdf5. So there must be something wrong with these files. I am going to close the issue now. Thank you for your time and the package.
